version: '3.1'

services:
  php-env:
    container_name: apps
    build: .
    volumes:
      - ./src:/var/www/html
    ports:
      - 9000:80
    links:
      - ragedb

  ragedb:
    container_name: ragedb
    image: mysql:5.7
    ports:
      - 3306:3306
    volumes:
      - ./dbDumps:/docker-entrypoint-initdb.d
    command:
      --default-authentication-plugin=mysql_native_password;
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ragedb
      MYSQL_USER: rage
      MYSQL_PASSWORD: rage
